---
title: Transcend
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: transcenduw@gmail.com
description: 'inspiring, facilitating, and developing student innovations.

'
baseurl: "/"
url: http://transcend.engineering
twitter_username: witranscend
github_username: transcend-engineering
facebook_username: transcendwi
email_address: transcenduw@gmail.com
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
